### ISSUE TITLE
todo

### ISSUE THREAD

**Issue by zhammer** [zhammer/writing#4]
- [ ] clearer navigation / scene numbers
- [ ] images coming out of text
- [ ] separate paragraphs for text
- [ ] use paragraph tag
- [ ] cleanup (manifest, metadata, etc.)
- [ ] help button (how to navigate page)
- [ ] navigation back to home
- [ ] on transition, go to top of page
- [ ] does yml tool allow a schema?
- [ ] scene slugs (maybe sluggification in app)
- [ ] netlify media for songs
